import { Database, FileCheck2, GitBranch, ShieldCheck, TestTube2, Workflow } from "lucide-react";
import PrecisionInfinityWorkflow from "./PrecisionInfinityWorkflow";

function Shell({tag,title,body,color,children}){return <article className="v5-component-card" style={{"--accent":color}}><div className="v5-component-copy"><span>{tag}</span><h3>{title}</h3><p>{body}</p></div><div className="v5-component-stage">{children}</div></article>}

function Labs(){return <Shell tag="COMPONENT 01" title="SecLabs · GoldenVault Systems" body="Purpose-bound isolated proving for applicability, attack relevance, treatment, monitoring, compatibility, rollback, recovery, and repeatable evidence without granting production authority." color="#32d8ed"><div className="v5-labs"><i/><i/><div><TestTube2/><b>SECLABS</b><small>GOLDENVAULT</small></div>{["STATE","TEST","EVIDENCE","RECOVER"].map((x,i)=><span key={x} style={{"--angle":`${i*90}deg`}}>{x}</span>)}</div></Shell>}
function Governance(){return <Shell tag="COMPONENT 02" title="Risk Governance Service Management" body="The integrated control plane for Production-Risk Cases, criteria, registers, domain tickets, authority, evidence, exceptions, residual risk, and assurance." color="#a276ff"><div className="v5-governance"><div className="v5-gov-core"><Database/><b>RISK</b><small>GOVERNANCE</small></div>{[["CRITERIA",ShieldCheck,"top"],["TICKETS",GitBranch,"left"],["AUTHORITY",Workflow,"right"],["REGISTERS",FileCheck2,"bottom"]].map(([x,I,p])=><span className={`v5-gov-node ${p}`} key={x}><I/>{x}</span>)}</div></Shell>}
function Lifecycle(){return <Shell tag="COMPONENT 03" title="ProdSecOps 8-Stage Workflow" body="One governed infinity lifecycle moves the Production-Risk Case from trusted context through isolated proving, decision, domain execution, and verified assurance." color="#38e2a8"><PrecisionInfinityWorkflow/></Shell>}
export default function FrameworkComponentVisuals(){return <div className="v5-component-grid"><Labs/><Governance/><Lifecycle/></div>}
